### PR TITLE
Fetch Entries from Manual Input CTA Spreadsheet

### LINKED ISSUE #88: Create spreadsheet scraper into DB for ingesting manual-entry objects

### PR DESCRIPTION
**Pull request by alexwilkinson**
Work in progress, but the goal of this PR is to create a rake task that will periodically fetch from a google spreadsheet of manually inputted data for the CTA Aggregator.

I have added a gem to handle the Google Sheets API (which is surprisingly strange), a Google service account for authenticating API requests, as well as lib classes for interacting with the gem API. Once we know more about exactly what data can be reasonably inputted by volunteers and what format it will take, we can start to add the actual logic for creating models from the spreadsheet rows.

Following this guide: https://www.twilio.com/blog/2017/03/google-spreadsheets-ruby.html
For those with Google app access, here's the service account credentials: https://console.developers.google.com/apis/credentials?project=hazel-strand-180721&authuser=1
Here's the gem: https://github.com/gimite/google-drive-ruby
And this is a helpful thread for how we're going to add the authentication details to Heroku, a somewhat unusual process since Google requires an actual JSON file for authentication: https://github.com/google/google-auth-library-ruby/issues/78

Closes #88.

### CODE REVIEW

**Comment by alexwilkinson** [comment]
The tests are failing in CI because we need to give Travis a placeholder ENV variable.

**Comment by bnd5k** [comment]
@alexwilkinson thank you for the PR!

We've been putting code that scrapes websites or imports data over in the `cta-scraper` app, located here: https://github.com/RagtagOpen/cta-scraper.

That app does the regularly scheduled rake tasks, which are listed here: https://github.com/RagtagOpen/cta-scraper/blob/develop/lib/tasks/scrape.rake.

The `cta-aggregator` repo is meant to be just the API and nothing else.  We wanted to give contributors the freedom to write scrapers in any language they wanted to, not just Ruby.   
 Having said that...currently, the only scrapers we have for the CTAA project are in Ruby.  But we're open to having Python scrapers, JS scrapers, etc. if that's how people are most comfortable contributing.

At any rate, I'm sorry that the confusion about where to put this spreadsheet PR.  I'll update the Readme on the cta-aggregator to make it clearer about the when something belongs in the scraper app.

Your code looks terrific.  Very clean. :)

**Comment by alexwilkinson** [comment]
Not a problem! Makes a lot of sense that it would go in that repository; I must’ve just gotten confused because the assigned issue was in this repo. I’ll re-make the PR over there : ).

Glad you like the code!

**Comment by bnd5k** [comment]
@alexwilkinson Also, we can set env variables for the CI system via that

**Pull request closed without merging**
